Controllers/CarrinhoController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCC_Sistema_Cliente_Jogos_2022.Models;
using TCC_Sistema_Cliente_Jogos_2022.Utils;
using TCC_Sistema_Cliente_Jogos_2022.ViewModels;

namespace TCC_Sistema_Cliente_Jogos_2022.Controllers
{

    public class CarrinhoController : Controller
    {
        // GET: Carrinho
        //VIEW DE TESTE
        //public ActionResult FazerCarrinho()
        //{
        //    return View();
        //}

        //VIEW DE TESTE
        //public ActionResult ColocarItemCarrinho()
        //{
        //    return View();
        //}

        [CustomAuthorize("Cliente")]
        //É SELECIONADO UM CARRINHO DO CLIENTE CADASTRADO E TENHA FEITO O LOGIN COM SEU CPF
        public ActionResult VerCarrinhoIndex(string CPF)
        {
            //UTILIZADO O OWIN PARA PEGAR O CPF LOGADO NO MOMENTO
            CPF = User.Identity.Name;
            if (!ModelState.IsValid)
            {
                return View(CPF);
            }
            var carr = new ItemCarrinho();

            //RETORNA O CARRINHO DOS ITENS COLOCADOS
            var carrinho = carr.ListarItemCarr(CPF);

            return View(carrinho);
        }

        [CustomAuthorize("Cliente")]
        //MÉTODO PARA ADICIONAR UM ITEM AO CARRINHO
        [HttpGet]
        public ActionResult AdicionarAOCarrinho(int codprod)
        {
            var CPFCliente = User.Identity.Name;
            var itemcar = new ItemCarrinho();
            
            //COM A UTILIZAÇÃO DO OWIN PARA PEGAR O CPF ATUAL, PEGA O ID DE PRODUTO PARA INSERIR NO CARRINHO E REDIRECIONA PARA A INDEX
            itemcar.ColocarItemCarrinho(codprod, CPFCliente);

            TempData["MensagemAviso"] = "Produto colocado com sucesso no carrinho! Acesse o link 'Ver Carrinho' para visualizar o carrinho";
            TempData["ConfirmaProduto"] = "Confirmado";
           return RedirectToAction("Index", "Home");

        }

        [CustomAuthorize("Cliente")]
        //FORMULÁRIO PARA REALIZAR A VENDA 
        public ActionResult FazerVenda()
        {
            MySqlConnection conexao = new MySqlConnection(ConfigurationManager.ConnectionStrings["conexaobd"].ConnectionString);
            try
            {
                conexao.Open();
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", new { mensagem = e.Message });
            }
            finally
            {
                if (conexao.State == ConnectionState.Open)
                    conexao.Close();
            }
            return View();
        }

        //UTILIZA O OBJETO DA VENDA DO FORMULÁRIO PARA ENVIAR EM UM MÉTODO DA MODEL
        [HttpPost]
        public ActionResult FazerVenda(Venda ven)
        {
            ven.fk_Clinte_CPF = User.Identity.Name;

            //if (!ModelState.IsValid)
            //{
            //    return View(ven);
            //}
            Venda venda = new Venda
            {
                FormaPag = ven.FormaPag,
                Parcela = ven.Parcela,
                fk_Clinte_CPF = ven.fk_Clinte_CPF
            };

            venda.FazerVenda(venda);

            //FAZ O TEMPDATA NOTIFICAR O USUÁRIO PARA A VENDA FEITA E REDIRECIONAR ELE PARA A CONSULTA DAS VENDAS
            TempData["MensagemAviso"] = "Compra feita com sucesso!";
            TempData["ConfirmaProduto"] = null;
            return RedirectToAction("Index", "Home");
        }

        //MÉTODO COM VIEW PARA VISUALIZAR A CONSULTA DE VENDAS SEM FILTRO
        [CustomAuthorize("Funcionario")]
        public ActionResult ConsulVenda(string CPFCli)
        {
            MySqlConnection conexao = new MySqlConnection(ConfigurationManager.ConnectionStrings["conexaobd"].ConnectionString);
            try
            {
                conexao.Open();
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", new { mensagem = e.Message });
            }
            finally
            {
                if (conexao.State == ConnectionState.Open)
                    conexao.Close();
            }
            var ven = new Venda();

            if (CPFCli != null)
            {
                var MostrarVendaPeloCPF = ven.ListarVendasPeloCPFCliente(CPFCli);

                return View(MostrarVendaPeloCPF);
            }

            var MostrarVenda = ven.ListarTodasVendas();

            return View(MostrarVenda);
        }

        public ActionResult Error(string mensagem)
        {
            ViewBag.error = "Entre em contato com um profissional TI e passe a seguinte mensagem: {" + mensagem + "}";
            return View();
        }

    }
}

Controllers/CupomController.cs
using Antlr.Runtime.Misc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCC_Sistema_Cliente_Jogos_2022.Models;
using TCC_Sistema_Cliente_Jogos_2022.Utils;

namespace TCC_Sistema_Cliente_Jogos_2022.Controllers
{
    [CustomAuthorize("Funcionario")]
    public class CupomController : Controller
    {
        // GET: Cupom

        //FAZ A CONSULTA DE CUPONS SEM FILTRO
        public ActionResult ConsulCupom(string NomeCup)
        {


            var cup = new Cupom();

            if (NomeCup != null)
            {
                var MostrarCupomPeloNome = cup.ListarCupPeloNome(NomeCup);

                return View(MostrarCupomPeloNome);
            }

            var MostrarCupom = cup.ListarCup();

            return View(MostrarCupom);
        }


        //FORMULÁRIO PARA ADICIONAR O CUPOM
        public ActionResult CadCupom()
        {
            return View();
        }

        //REALIZA O CADASTRO DO CUPOM
        [HttpPost]
        public ActionResult CadCupom(Cupom cup)
        {
            
            if (!ModelState.IsValid)
            {
                return View(cup);
            }
            Cupom cupom = new Cupom
            {
                CupomTxt = cup.CupomTxt,
                ValorCupom = cup.ValorCupom,
                NumLimiteCompras = cup.NumLimiteCompras,
            };
            //É ENVIADO UM OBJETO COM OS DADOS DO PARÂMETRO E REDIRECIONA O USUÁRIO PARA A TABELA DE CONSULTA COM UMA NOTIFICAÇÃO DA TEMPDATA
            cupom.CadastrarCup(cup);

            TempData["MensagemAviso"] = "Cadastro do cupom feito com sucesso!";
            return RedirectToAction("ConsulCupom");
        }

        //FORMULÁRIO PARA ALTERAR O CUPOM ESPECÍFICO PELO PARÂMETRO
        [HttpGet]
        public ActionResult EdiCupom(int codcupom)
        {
            Cupom cup = new Cupom();

            var umcupom = cup.ListaUMCupom(codcupom);

            if (umcupom == null)
                return HttpNotFound();

            return View(umcupom);
        }


        //MÉTODO PARA REALIZAR A ALTERAÇÃO DO CUPOM
        [HttpPost]
        public ActionResult EdiCupom(Cupom cupom)
        {
            if (!ModelState.IsValid)
            {
                return View(cupom);
            }
            Cupom cup = new Cupom();

            cup.AlterarCup(cupom);

            //É ENVIADO UM OBJETO COM OS DADOS ALTERADOS E REDIRECIONA O USUÁRIO PARA A TABELA DE CONSULTA COM UMA NOTIFICAÇÃO DA TEMPDATA
            TempData["MensagemAviso"] = "Alteração do Cupom feito com sucesso!";
            return RedirectToAction("ConsulCupom");
        }

        //FAZ APAGAR O CUPOM
        
        public ActionResult DelCupom(int codcupom)
        {
            var cup = new Cupom();

            cup.DeletarCup(codcupom);


            //EMITE UM AVO AO USUÁRIO SOBRE O CUPOM APAGADO E REDIRECIONA PARA A CONSULTA DELES
            TempData["MensagemAviso"] = "Cupom deletado com sucesso!";
            return RedirectToAction("ConsulCupom");
        }

        public ActionResult Error(string mensagem)
        {
            ViewBag.error = "Entre em contato com um profissional TI e passe a seguinte mensagem: {" + mensagem + "}";
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Games Wave</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/Image/Icone.ico" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <!--ABAIXO É A NAVBAR-->
    <nav class="navbar navbar-inverse" id="navBar">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".container-fluid" title="more options">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("Index", "Login")"><img src="~/Image/logogameswave.png" alt="logo" id="logo"></a>
        </div>
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Login")">Home</a>
            </div>
            <ul class="nav navbar-nav" id="herderNav">
                <li><a href="#">Promoções</a></li>
                <li><a href="#">Novos</a></li>
                <li><a href="#">Lançamentos</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <!--Barra de pesquisa-->
                <div class="navbar-form navbar-left" id="formPesquisa">
                    @using (Html.BeginForm("Index", "Login", FormMethod.Get))
                    {
                        <form>
                            <div class="input-group">
                                <input type="text" class="form-control" id="spPesquia" name="spPesquia" placeholder="Pesquise..." />
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <i class="glyphicon glyphicon-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    }
                </div>


                @if (User.Identity.IsAuthenticated)
                {
                    <!--Dropdown-->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Painel do funcionario<span class="caret"></span></a>
                        <ul class="dropdown-menu">         
                            <li> @Html.ActionLink("Consultar Funcionários", "ConsulFuncio", "Funcionario")</li>
                            <li>@Html.ActionLink("Consultar Clientes", "ConsulCli", "Cliente")</li>
                            <li>@Html.ActionLink("Consultar Produtos", "ConsulProduto", "Produto")</li>
                            @*<li>@Html.ActionLink("Ver Carrinho", "VerCarrinhoIndex", "Carrinho")</li>
                            <li>@Html.ActionLink("Fazer Venda", "FazerVenda", "Carrinho")</li>*@
                            <li>@Html.ActionLink("Consultar Vendas", "ConsulVenda", "Carrinho")</li>
                            <li>@Html.ActionLink("Consultar Cupons", "ConsulCupom", "Cupom")</li>
                        </ul>
                   </li>
                <li><a href="@Url.Action("Logout", "Login")"><img id="imgHeader" src="~/Image/log_out.png" alt="Carrinho"></a></li>
                @*<li><a href="@Url.Action("VerCarrinhoIndex", "Carrinho")"><img id="imgHeader" src="~/Image/shopping-cart (1).png" alt="Carrinho"></a></li>*@

            }
            else
            {
                <li><a class="nav-link" href="@Url.Action("Login", "Login")"><img id="imgHeader" src="~/Image/user (1).png" alt="user"></a></li>

            }
                </ul>
            </div>
    </nav>
    <!--ACIMA É A NAVBAR-->
    <div class="container body-content">
        @RenderBody()
    </div>


    <!-- Site footer -->
    <footer class="site-footer">
        <div class="containerFooter">
            <div class="row">
                <div class="col-xs-6 col-md-5" id="descFooter">
                    <h6>Nossa empresa</h6>
                    <p class="text-justify">Fundada em 2022, aspiramos dar uma melhor interface e experiência para nossos amados clientes.  </p>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Categorias</h6>
                    <ul class="footer-links">
                        <li><a href="@Url.Action("Index", "Login")">Home</a></li>
                        <li><a href="@Url.Action("Index", "Login")">Sobre</a></li>
                        <li><a href="@Url.Action("Login", "Login")">Login</a></li>
                        <li><a href="@Url.Action("Index", "Login")">Contato</a></li>
                        <li><a href="@Url.Action("Index", "Login")">Categorias</a></li>
                    </ul>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Entre em contato</h6>
                    <ul class="footer-links">
                        <li><a href="#">Rua Ausgusta, 69, São Paulo</a></li>
                        <li><a href="#"> game.wave@gmail.com </a></li>
                        <li><a href="#">(11) 968425-7725</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
            <hr>
        </div>
        <div class="containerFooter">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">
                        Copyright &copy;  @DateTime.Now.Year All Rights Reserved by
                        <a href="#">DEVELOPED BY HORIZON SYSTEMS LTDA.</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout_Acesso_Restrito.cshtml
Acesso restrito

Views/Shared/_Layout_Cliente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Games Wave</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/Image/Icone.ico" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <!--ABAIXO É A NAVBAR-->
    <nav class="navbar navbar-inverse" id="navBar">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".container-fluid" title="more options">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("Index", "Home")"><img src="~/Image/logogameswave.png" alt="logo" id="logo"></a>
        </div>
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">Home</a>
            </div>
            <ul class="nav navbar-nav" id="herderNav">
                <li><a href="#">Promoções</a></li>
                <li><a href="#">Novos</a></li>
                <li><a href="#">Lançamentos</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <!--Barra de pesquisa-->
                <div class="navbar-form navbar-left" id="formPesquisa">
                    @using (Html.BeginForm("Index", "Home", FormMethod.Get))
                    {
                        <form>
                            <div class="input-group">
                                <input type="text" class="form-control" id="spPesquia" name="spPesquia" placeholder="Pesquise..." />
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <i class="glyphicon glyphicon-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    }
                </div>


                @if (User.Identity.IsAuthenticated)
                {
                    <!--Dropdown-->
                    @*<li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Painel do funcionario<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li> @Html.ActionLink("Consultar Funcionarios", "ConsulFuncio", "Funcionario")</li>
                            <li>@Html.ActionLink("Consultar Clientes", "ConsulCli", "Cliente")</li>
                            <li>@Html.ActionLink("Consultar Produtos", "ConsulProduto", "Produto")</li>
                            <li>@Html.ActionLink("Ver Carrinho", "VerCarrinhoIndex", "Carrinho")</li>
                            <li>@Html.ActionLink("Fazer Venda", "FazerVenda", "Carrinho")</li>
                            <li>@Html.ActionLink("Consultar Vendas", "ConsulVenda", "Carrinho")</li>
                            <li>@Html.ActionLink("Consultar Cupons", "ConsulCupom", "Cupom")</li>
                        </ul>
                    </li>*@
                    <li><a href="@Url.Action("Logout", "Login")"><img id="imgHeader" src="~/Image/log_out.png" alt="Carrinho"></a></li>
                    <li><a href="@Url.Action("VerCarrinhoIndex", "Carrinho")"><img id="imgHeader" src="~/Image/shopping-cart (1).png" alt="Carrinho"></a></li>

                }
                else
                {
                    <li><a class="nav-link" href="@Url.Action("Login", "Login")"><img id="imgHeader" src="~/Image/user (1).png" alt="user"></a></li>

                }
            </ul>
        </div>
    </nav>
    <!--ACIMA É A NAVBAR-->
    <div class="container body-content">
        @RenderBody()
    </div>


    <!-- Site footer -->
    <footer class="site-footer">
        <div class="containerFooter">
            <div class="row">
                <div class="col-xs-6 col-md-5" id="descFooter">
                    <h6>Nossa empresa</h6>
                    <p class="text-justify">Fundada em 2022, aspiramos dar uma melhor interface e experiencia para nossos amados clientes.  </p>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Categorias</h6>
                    <ul class="footer-links">
                        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                        <li><a href="@Url.Action("Index", "Home")">Sobre</a></li>
                        <li><a href="@Url.Action("Login", "Home")">Login</a></li>
                        <li><a href="@Url.Action("Index", "Home")">Contato</a></li>
                        <li><a href="@Url.Action("Index", "Home")">Categorias</a></li>
                    </ul>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Entre em contato</h6>
                    <ul class="footer-links">
                        <li><a href="#">Rua Ausgusta, 69, São Paulo</a></li>
                        <li><a href="#"> game.wave@gmail.com </a></li>
                        <li><a href="#">(11) 968425-7725</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
            <hr>
        </div>
        <div class="containerFooter">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">
                        Copyright &copy;  @DateTime.Now.Year All Rights Reserved by
                        <a href="#">DEVELOPED BY HORIZON SYSTEMS LTDA.</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout_Login_navbar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Games Wave</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/Image/Icone.ico" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <!--ABAIXO É A NAVBAR-->
    <nav class="navbar navbar-inverse" id="navBar">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".container-fluid" title="more options">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#"><img src="~/Image/logogameswave.png" alt="logo" id="logo"></a>
        </div>
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Home</a>
            </div>
            <ul class="nav navbar-nav" id="herderNav">
                <li><a href="#">Promoções</a></li>
                <li><a href="#">Novos</a></li>
                <li><a href="#">Lançamentos</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <!--Barra de pesquisa-->
                @*<div class="navbar-form navbar-left" id="formPesquisa">
                    @using (Html.BeginForm("Index", "Home", FormMethod.Get))
                    {
                        <form>
                            <div class="input-group">
                                <input type="text" class="form-control" id="spPesquia" name="spPesquia" placeholder="Pesquise..." />
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <i class="glyphicon glyphicon-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    }
                </div>*@


                @if (User.Identity.IsAuthenticated)
                {
                    <!--Dropdown-->
                    @*<li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Painel do funcionario<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li> @Html.ActionLink("Consultar Funcionarios", "ConsulFuncio", "Funcionario")</li>
                                <li>@Html.ActionLink("Consultar Clientes", "ConsulCli", "Cliente")</li>
                                <li>@Html.ActionLink("Consultar Produtos", "ConsulProduto", "Produto")</li>
                                <li>@Html.ActionLink("Ver Carrinho", "VerCarrinhoIndex", "Carrinho")</li>
                                <li>@Html.ActionLink("Fazer Venda", "FazerVenda", "Carrinho")</li>
                                <li>@Html.ActionLink("Consultar Vendas", "ConsulVenda", "Carrinho")</li>
                                <li>@Html.ActionLink("Consultar Cupons", "ConsulCupom", "Cupom")</li>
                            </ul>
                        </li>*@
                    <li><a href="@Url.Action("Logout", "Login")"><img id="imgHeader" src="~/Image/log_out.png" alt="Carrinho"></a></li>
                    <li><a href="@Url.Action("VerCarrinhoIndex", "Carrinho")"><img id="imgHeader" src="~/Image/shopping-cart (1).png" alt="Carrinho"></a></li>

                }
                else
                {
                    <li><a class="nav-link" href="@Url.Action("Login", "Login")"><img id="imgHeader" src="~/Image/user (1).png" alt="user"></a></li>

                }
            </ul>
        </div>
    </nav>
    <!--ACIMA É A NAVBAR-->
    <div class="container body-content">
        @RenderBody()
    </div>


    <!-- Site footer -->
    <footer class="site-footer">
        <div class="containerFooter">
            <div class="row">
                <div class="col-xs-6 col-md-5" id="descFooter">
                    <h6>Nossa empresa</h6>
                    <p class="text-justify">Fundada em 2022, aspiramos dar uma melhor interface e experiência para nossos amados clientes.  </p>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Guias rápidos</h6>
                    <ul class="footer-links">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Sobre</a></li>
                        <li><a href="#">Login</a></li>
                        <li><a href="#">Contato</a></li>
                        <li><a href="#">Categorias</a></li>
                    </ul>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Entre em contato</h6>
                    <ul class="footer-links">
                        <li><a href="#">Rua Ausgusta, 69, São Paulo</a></li>
                        <li><a href="#"> game.wave@gmail.com </a></li>
                        <li><a href="#">(11) 968425-7725</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
            <hr>
        </div>
        <div class="containerFooter">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">
                        Copyright &copy;  @DateTime.Now.Year All Rights Reserved by
                        <a href="#">DEVELOPED BY HORIZON SYSTEMS LTDA.</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>